### ISSUE TITLE
c++1z

### ISSUE THREAD

**Issue by JurianBruinink** [dsperados/homebrew-tap#1]
Hey!

I was taking a class from Ciska Vriezinga and I was trying to install dsperados via brew.
I got the following issue and she told me to send it to you:
I'm definitely missing something like the c++ compiler, could you please add how to install it?
Thanks!

Jurians-MacBook-Pro:tempSynthExample_sogm-master Jurian$ brew install bear-audio
==> Installing bear-audio from dsperados/tap
==> Downloading https://github.com/dsperados/bear-audio/archive/v0.1.0-alpha.2.t
Already downloaded: /Users/Jurian/Library/Caches/Homebrew/bear-audio-0.1.0-alpha.2.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make install
Last 15 lines from /Users/Jurian/Library/Logs/Homebrew/bear-audio/02.make:
[ 40%] Building CXX object CMakeFiles/bear-audio.dir/InputOutputProcessor.cpp.o
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Dbear_audio_EXPORTS -I/usr/local/include  -DNDEBUG -fPIC   -std=c++1z -Wall -o CMakeFiles/bear-audio.dir/Input.cpp.o -c /tmp/bear-audio-20161205-42159-1qd4qq4/bear-audio-0.1.0-alpha.2/Input.cpp
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Dbear_audio_EXPORTS -I/usr/local/include  -DNDEBUG -fPIC   -std=c++1z -Wall -o CMakeFiles/bear-audio.dir/File.cpp.o -c /tmp/bear-audio-20161205-42159-1qd4qq4/bear-audio-0.1.0-alpha.2/File.cpp
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Dbear_audio_EXPORTS -I/usr/local/include  -DNDEBUG -fPIC   -std=c++1z -Wall -o CMakeFiles/bear-audio.dir/InputOutputProcessor.cpp.o -c /tmp/bear-audio-20161205-42159-1qd4qq4/bear-audio-0.1.0-alpha.2/InputOutputProcessor.cpp
error: invalid value 'c++1z' in '-std=c++1z'
error: invalid value 'c++1z' in '-std=c++1z'
make[2]: *** [CMakeFiles/bear-audio.dir/InputCache.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/bear-audio.dir/InputOutputProcessor.cpp.o] Error 1
error: invalid value 'c++1z' in '-std=c++1z'
make[2]: *** [CMakeFiles/bear-audio.dir/Input.cpp.o] Error 1
error: invalid value 'c++1z' in '-std=c++1z'
make[2]: *** [CMakeFiles/bear-audio.dir/File.cpp.o] Error 1
make[1]: *** [CMakeFiles/bear-audio.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/dsperados/homebrew-tap/issues

**Comment by stijnfrishert** [comment]
Hi Jurrian! The problem's quite simple, your version of `clang` (the C++ compiler provided by Xcode) is out of date. I'm guessing your XCode version is below 7? If you update all issues should be resolved :)

**Comment by JurianBruinink** [comment]
That will be it! I'm not using XCode at all as I work with a different editor.

I'll update it and see if it works. thanks for the fast reply!


________________________________

**Comment by stijnfrishert** [comment]
Ah, ok! No problem! Glad there's more people trying our stuff out :D

(The C++ compiler (clang) that comes with macOS is updated by updating XCode, even if you don't use XCode.)

**Comment by JurianBruinink** [comment]
Allright thanks! it worked.
I'll keep my xcode updated from now on ;)

**Comment by stijnfrishert** [comment]
Good to know! Enjoy :)
