### ISSUE TITLE
raspbian - brew install grizzly fails

### ISSUE THREAD

**Issue by ciskavriezenga** [dsperados/homebrew-tap#3]
On Raspbian - Jessie, brew install grizzly fails. 
Seems to be an issue with cmath, probably nothing to do with grizzly. 
Creating this issue to keep track of possible obstacles when working on raspberry pi.

terminal log: 

==> Installing grizzly from dsperados/tap
==> Downloading https://github.com/dsperados/grizzly/archive/v0.1.0-alpha.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/grizzly-v0.1.0-alpha.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make install
Last 15 lines from /home/pi/.cache/Homebrew/Logs/grizzly/02.make:
/usr/include/c++/6/cmath:1242:11: error: ‘::truncf’ has not been declared
   using ::truncf;
           ^~~~~~
/usr/include/c++/6/cmath:1243:11: error: ‘::truncl’ has not been declared
   using ::truncl;
           ^~~~~~
CMakeFiles/grizzly.dir/build.make:113: recipe for target 'CMakeFiles/grizzly.dir/Ooura/fftsg.cpp.o' failed
make[2]: *** [CMakeFiles/grizzly.dir/Ooura/fftsg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/grizzly-20170223-3146-7z7677/grizzly-0.1.0-alpha'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/grizzly.dir/all' failed
make[1]: *** [CMakeFiles/grizzly.dir/all] Error 2
make[1]: Leaving directory '/tmp/grizzly-20170223-3146-7z7677/grizzly-0.1.0-alpha'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/dsperados/homebrew-tap/issues

These open issues may also help:
raspbian - brew install grizzly fails https://github.com/dsperados/homebrew-tap/issues/3

**Comment by ciskavriezenga** [comment]
could this be related to the C++17 nested namespaces?
```using ::truncf``` seems a nested format to me and that part is 'not declared'..

**Comment by ciskavriezenga** [comment]
without brew, cmake works fine, but ```$ make``` get stuck: 



pi@Api:~/Code/git/dsperados/grizzly/build $ make
[ 25%] Building CXX object CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o
c++: error: unrecognized command line option ‘-std=c++1z’
CMakeFiles/grizzly.dir/build.make:62: recipe for target 'CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o' failed
make[2]: *** [CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/grizzly.dir/all' failed
make[1]: *** [CMakeFiles/grizzly.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2





seems like g++-6 is not called, because of ```unrecognized command line option ‘-std=c++1z’```. 
This problem still exists after ```alias c++='g++-6'```. Don't know which c++ compiler cmake uses

**Comment by DannyvanSwieten** [comment]
Can you try:
export CXX=/usr/local/bin/g++
before running CMake?

**Comment by ciskavriezenga** [comment]
After removing build/ directory and rerunning cmake like this: 
``` CXX=g++-6 cmake ..```
I don't get the ```-std=c++1z``` error anymore.

**Comment by ciskavriezenga** [comment]
@Danny I already had above comment ready, but am now wrestling with building the dependencies.

**Comment by ciskavriezenga** [comment]
Grizzly needs math, which needs geometry: 
[ 25%] Building CXX object CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o
In file included from /home/pi/Code/git/dsperados/grizzly/FastFourierTransformBase.cpp:30:0:
/home/pi/Code/git/dsperados/grizzly/FastFourierTransformBase.hpp:33:41: fatal error: dsperados/math/interleave.hpp: No such file or directory
 #include <dsperados/math/interleave.hpp>
                                         ^
compilation terminated.
CMakeFiles/grizzly.dir/build.make:62: recipe for target 'CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o' failed
make[2]: *** [CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/grizzly.dir/all' failed
make[1]: *** [CMakeFiles/grizzly.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2



I need to build those libraries first right? After running make for geometry, should I relocate something to enable math to find the geometry headers?

**Comment by DannyvanSwieten** [comment]
now you've exported the CXX variable you could try running the brew formula again

**Comment by ciskavriezenga** [comment]
hmm no, then I get the first error again, with the 
```/usr/include/c++/6/cmath:1242:11: error: ‘::truncf’ has not been declared
using ::truncf;```
See initial comment

**Comment by DannyvanSwieten** [comment]
Ok, well math depends on geometry so:
geometry, then math, then grizzly.
Relocation shouldn't be required

**Comment by ciskavriezenga** [comment]
I tried it already:

In the following directory I cloned grizzly, math and geometry (-> cloned in sub directories).
/home/pi/Code/git/dsperados/
I ran cmake (successfully), and make (no errors).
I then went to /home/pi/Code/git/dsperados/math. Error: a geometry header is not found.

Should I build the geometry lib at a different location? And is the build result the libgeometry.a file?

**Comment by ciskavriezenga** [comment]
Hmm can't re edit a comment on my phone, the successful cmake and build was with geometry

**Comment by DannyvanSwieten** [comment]
And install?

**Comment by ciskavriezenga** [comment]
Damn, so focused on the other stuff that I totally forgot about that step 😖, will try it tonight/tomorrow!

**Comment by ciskavriezenga** [comment]
builded  & installed geometry & math libs. 
Same type errors rise when I run make on grizzly, see terminal log below:



pi@Api:~/Code/git/dsperados/grizzly/build $ make 
Scanning dependencies of target grizzly
[ 25%] Building CXX object CMakeFiles/grizzly.dir/FastFourierTransformBase.cpp.o
[ 50%] Building CXX object CMakeFiles/grizzly.dir/Ooura/FastFourierTransformOoura.cpp.o
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp: In member function ‘virtual void dsp::FastFourierTransformOoura::forward(const float*, float*, float*)’:
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp:55:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < size / 2; ++i)
                          ~~^~~~~~~~~~
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp: In member function ‘virtual void dsp::FastFourierTransformOoura::forward(const double*, double*, double*)’:
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp:72:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < size / 2; ++i)
                          ~~^~~~~~~~~~
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp: In member function ‘virtual void dsp::FastFourierTransformOoura::inverse(const float*, const float*, float*)’:
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp:85:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < size / 2; ++i)
                          ~~^~~~~~~~~~
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp: In member function ‘virtual void dsp::FastFourierTransformOoura::inverse(const double*, const double*, double*)’:
/home/pi/Code/git/dsperados/grizzly/Ooura/FastFourierTransformOoura.cpp:103:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (auto i = 0; i < size / 2; ++i)
                          ~~^~~~~~~~~~
[ 75%] Building CXX object CMakeFiles/grizzly.dir/Ooura/fftsg.cpp.o
In file included from /usr/include/c++/6/math.h:36:0,
                 from /home/pi/Code/git/dsperados/grizzly/Ooura/fftsg.cpp:393:
/usr/include/c++/6/cmath:106:11: error: ‘::acos’ has not been declared
   using ::acos;
           ^~~~
/usr/include/c++/6/cmath:125:11: error: ‘::asin’ has not been declared
   using ::asin;
           ^~~~
/usr/include/c++/6/cmath:144:11: error: ‘::atan’ has not been declared
   using ::atan;
           ^~~~
/usr/include/c++/6/cmath:163:11: error: ‘::atan2’ has not been declared
   using ::atan2;
           ^~~~~
/usr/include/c++/6/cmath:184:11: error: ‘::ceil’ has not been declared
   using ::ceil;
           ^~~~
/usr/include/c++/6/cmath:203:11: error: ‘::cos’ has not been declared
   using ::cos;
           ^~~
/usr/include/c++/6/cmath:222:11: error: ‘::cosh’ has not been declared
   using ::cosh;
           ^~~~
/usr/include/c++/6/cmath:241:11: error: ‘::exp’ has not been declared
   using ::exp;
           ^~~
/usr/include/c++/6/cmath:260:11: error: ‘::fabs’ has not been declared
   using ::fabs;
           ^~~~
/usr/include/c++/6/cmath:279:11: error: ‘::floor’ has not been declared
   using ::floor;
           ^~~~~
/usr/include/c++/6/cmath:298:11: error: ‘::fmod’ has not been declared
   using ::fmod;
           ^~~~
/usr/include/c++/6/cmath:319:11: error: ‘::frexp’ has not been declared
   using ::frexp;
           ^~~~~
/usr/include/c++/6/cmath:338:11: error: ‘::ldexp’ has not been declared
   using ::ldexp;
           ^~~~~
/usr/include/c++/6/cmath:357:11: error: ‘::log’ has not been declared
   using ::log;
           ^~~
/usr/include/c++/6/cmath:376:11: error: ‘::log10’ has not been declared
   using ::log10;
           ^~~~~
/usr/include/c++/6/cmath:395:11: error: ‘::modf’ has not been declared
   using ::modf;
           ^~~~
/usr/include/c++/6/cmath:407:11: error: ‘::pow’ has not been declared
   using ::pow;
           ^~~
/usr/include/c++/6/cmath:444:11: error: ‘::sin’ has not been declared
   using ::sin;
           ^~~
/usr/include/c++/6/cmath:463:11: error: ‘::sinh’ has not been declared
   using ::sinh;
           ^~~~
/usr/include/c++/6/cmath:482:11: error: ‘::sqrt’ has not been declared
   using ::sqrt;
           ^~~~
/usr/include/c++/6/cmath:501:11: error: ‘::tan’ has not been declared
   using ::tan;
           ^~~
/usr/include/c++/6/cmath:520:11: error: ‘::tanh’ has not been declared
   using ::tanh;
           ^~~~
/usr/include/c++/6/cmath:1101:11: error: ‘::double_t’ has not been declared
   using ::double_t;
           ^~~~~~~~
/usr/include/c++/6/cmath:1102:11: error: ‘::float_t’ has not been declared
   using ::float_t;
           ^~~~~~~
/usr/include/c++/6/cmath:1105:11: error: ‘::acosh’ has not been declared
   using ::acosh;
           ^~~~~
/usr/include/c++/6/cmath:1106:11: error: ‘::acoshf’ has not been declared
   using ::acoshf;
           ^~~~~~
/usr/include/c++/6/cmath:1107:11: error: ‘::acoshl’ has not been declared
   using ::acoshl;
           ^~~~~~
/usr/include/c++/6/cmath:1109:11: error: ‘::asinh’ has not been declared
   using ::asinh;
           ^~~~~
/usr/include/c++/6/cmath:1110:11: error: ‘::asinhf’ has not been declared
   using ::asinhf;
           ^~~~~~
/usr/include/c++/6/cmath:1111:11: error: ‘::asinhl’ has not been declared
   using ::asinhl;
           ^~~~~~
/usr/include/c++/6/cmath:1113:11: error: ‘::atanh’ has not been declared
   using ::atanh;
           ^~~~~
/usr/include/c++/6/cmath:1114:11: error: ‘::atanhf’ has not been declared
   using ::atanhf;
           ^~~~~~
/usr/include/c++/6/cmath:1115:11: error: ‘::atanhl’ has not been declared
   using ::atanhl;
           ^~~~~~
/usr/include/c++/6/cmath:1117:11: error: ‘::cbrt’ has not been declared
   using ::cbrt;
           ^~~~
/usr/include/c++/6/cmath:1118:11: error: ‘::cbrtf’ has not been declared
   using ::cbrtf;
           ^~~~~
/usr/include/c++/6/cmath:1119:11: error: ‘::cbrtl’ has not been declared
   using ::cbrtl;
           ^~~~~
/usr/include/c++/6/cmath:1121:11: error: ‘::copysign’ has not been declared
   using ::copysign;
           ^~~~~~~~
/usr/include/c++/6/cmath:1122:11: error: ‘::copysignf’ has not been declared
   using ::copysignf;
           ^~~~~~~~~
/usr/include/c++/6/cmath:1123:11: error: ‘::copysignl’ has not been declared
   using ::copysignl;
           ^~~~~~~~~
/usr/include/c++/6/cmath:1125:11: error: ‘::erf’ has not been declared
   using ::erf;
           ^~~
/usr/include/c++/6/cmath:1126:11: error: ‘::erff’ has not been declared
   using ::erff;
           ^~~~
/usr/include/c++/6/cmath:1127:11: error: ‘::erfl’ has not been declared
   using ::erfl;
           ^~~~
/usr/include/c++/6/cmath:1129:11: error: ‘::erfc’ has not been declared
   using ::erfc;
           ^~~~
/usr/include/c++/6/cmath:1130:11: error: ‘::erfcf’ has not been declared
   using ::erfcf;
           ^~~~~
/usr/include/c++/6/cmath:1131:11: error: ‘::erfcl’ has not been declared
   using ::erfcl;
           ^~~~~
/usr/include/c++/6/cmath:1133:11: error: ‘::exp2’ has not been declared
   using ::exp2;
           ^~~~
/usr/include/c++/6/cmath:1134:11: error: ‘::exp2f’ has not been declared
   using ::exp2f;
           ^~~~~
/usr/include/c++/6/cmath:1135:11: error: ‘::exp2l’ has not been declared
   using ::exp2l;
           ^~~~~
/usr/include/c++/6/cmath:1137:11: error: ‘::expm1’ has not been declared
   using ::expm1;
           ^~~~~
/usr/include/c++/6/cmath:1138:11: error: ‘::expm1f’ has not been declared
   using ::expm1f;
           ^~~~~~
/usr/include/c++/6/cmath:1139:11: error: ‘::expm1l’ has not been declared
   using ::expm1l;
           ^~~~~~
/usr/include/c++/6/cmath:1141:11: error: ‘::fdim’ has not been declared
   using ::fdim;
           ^~~~
/usr/include/c++/6/cmath:1142:11: error: ‘::fdimf’ has not been declared
   using ::fdimf;
           ^~~~~
/usr/include/c++/6/cmath:1143:11: error: ‘::fdiml’ has not been declared
   using ::fdiml;
           ^~~~~
/usr/include/c++/6/cmath:1145:11: error: ‘::fma’ has not been declared
   using ::fma;
           ^~~
/usr/include/c++/6/cmath:1146:11: error: ‘::fmaf’ has not been declared
   using ::fmaf;
           ^~~~
/usr/include/c++/6/cmath:1147:11: error: ‘::fmal’ has not been declared
   using ::fmal;
           ^~~~
/usr/include/c++/6/cmath:1149:11: error: ‘::fmax’ has not been declared
   using ::fmax;
           ^~~~
/usr/include/c++/6/cmath:1150:11: error: ‘::fmaxf’ has not been declared
   using ::fmaxf;
           ^~~~~
/usr/include/c++/6/cmath:1151:11: error: ‘::fmaxl’ has not been declared
   using ::fmaxl;
           ^~~~~
/usr/include/c++/6/cmath:1153:11: error: ‘::fmin’ has not been declared
   using ::fmin;
           ^~~~
/usr/include/c++/6/cmath:1154:11: error: ‘::fminf’ has not been declared
   using ::fminf;
           ^~~~~
/usr/include/c++/6/cmath:1155:11: error: ‘::fminl’ has not been declared
   using ::fminl;
           ^~~~~
/usr/include/c++/6/cmath:1157:11: error: ‘::hypot’ has not been declared
   using ::hypot;
           ^~~~~
/usr/include/c++/6/cmath:1158:11: error: ‘::hypotf’ has not been declared
   using ::hypotf;
           ^~~~~~
/usr/include/c++/6/cmath:1159:11: error: ‘::hypotl’ has not been declared
   using ::hypotl;
           ^~~~~~
/usr/include/c++/6/cmath:1161:11: error: ‘::ilogb’ has not been declared
   using ::ilogb;
           ^~~~~
/usr/include/c++/6/cmath:1162:11: error: ‘::ilogbf’ has not been declared
   using ::ilogbf;
           ^~~~~~
/usr/include/c++/6/cmath:1163:11: error: ‘::ilogbl’ has not been declared
   using ::ilogbl;
           ^~~~~~
/usr/include/c++/6/cmath:1165:11: error: ‘::lgamma’ has not been declared
   using ::lgamma;
           ^~~~~~
/usr/include/c++/6/cmath:1166:11: error: ‘::lgammaf’ has not been declared
   using ::lgammaf;
           ^~~~~~~
/usr/include/c++/6/cmath:1167:11: error: ‘::lgammal’ has not been declared
   using ::lgammal;
           ^~~~~~~
/usr/include/c++/6/cmath:1169:11: error: ‘::llrint’ has not been declared
   using ::llrint;
           ^~~~~~
/usr/include/c++/6/cmath:1170:11: error: ‘::llrintf’ has not been declared
   using ::llrintf;
           ^~~~~~~
/usr/include/c++/6/cmath:1171:11: error: ‘::llrintl’ has not been declared
   using ::llrintl;
           ^~~~~~~
/usr/include/c++/6/cmath:1173:11: error: ‘::llround’ has not been declared
   using ::llround;
           ^~~~~~~
/usr/include/c++/6/cmath:1174:11: error: ‘::llroundf’ has not been declared
   using ::llroundf;
           ^~~~~~~~
/usr/include/c++/6/cmath:1175:11: error: ‘::llroundl’ has not been declared
   using ::llroundl;
           ^~~~~~~~
/usr/include/c++/6/cmath:1177:11: error: ‘::log1p’ has not been declared
   using ::log1p;
           ^~~~~
/usr/include/c++/6/cmath:1178:11: error: ‘::log1pf’ has not been declared
   using ::log1pf;
           ^~~~~~
/usr/include/c++/6/cmath:1179:11: error: ‘::log1pl’ has not been declared
   using ::log1pl;
           ^~~~~~
/usr/include/c++/6/cmath:1181:11: error: ‘::log2’ has not been declared
   using ::log2;
           ^~~~
/usr/include/c++/6/cmath:1182:11: error: ‘::log2f’ has not been declared
   using ::log2f;
           ^~~~~
/usr/include/c++/6/cmath:1183:11: error: ‘::log2l’ has not been declared
   using ::log2l;
           ^~~~~
/usr/include/c++/6/cmath:1185:11: error: ‘::logb’ has not been declared
   using ::logb;
           ^~~~
/usr/include/c++/6/cmath:1186:11: error: ‘::logbf’ has not been declared
   using ::logbf;
           ^~~~~
/usr/include/c++/6/cmath:1187:11: error: ‘::logbl’ has not been declared
   using ::logbl;
           ^~~~~
/usr/include/c++/6/cmath:1189:11: error: ‘::lrint’ has not been declared
   using ::lrint;
           ^~~~~
/usr/include/c++/6/cmath:1190:11: error: ‘::lrintf’ has not been declared
   using ::lrintf;
           ^~~~~~
/usr/include/c++/6/cmath:1191:11: error: ‘::lrintl’ has not been declared
   using ::lrintl;
           ^~~~~~
/usr/include/c++/6/cmath:1193:11: error: ‘::lround’ has not been declared
   using ::lround;
           ^~~~~~
/usr/include/c++/6/cmath:1194:11: error: ‘::lroundf’ has not been declared
   using ::lroundf;
           ^~~~~~~
/usr/include/c++/6/cmath:1195:11: error: ‘::lroundl’ has not been declared
   using ::lroundl;
           ^~~~~~~
/usr/include/c++/6/cmath:1197:11: error: ‘::nan’ has not been declared
   using ::nan;
           ^~~
/usr/include/c++/6/cmath:1198:11: error: ‘::nanf’ has not been declared
   using ::nanf;
           ^~~~
/usr/include/c++/6/cmath:1199:11: error: ‘::nanl’ has not been declared
   using ::nanl;
           ^~~~
/usr/include/c++/6/cmath:1201:11: error: ‘::nearbyint’ has not been declared
   using ::nearbyint;
           ^~~~~~~~~
/usr/include/c++/6/cmath:1202:11: error: ‘::nearbyintf’ has not been declared
   using ::nearbyintf;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1203:11: error: ‘::nearbyintl’ has not been declared
   using ::nearbyintl;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1205:11: error: ‘::nextafter’ has not been declared
   using ::nextafter;
           ^~~~~~~~~
/usr/include/c++/6/cmath:1206:11: error: ‘::nextafterf’ has not been declared
   using ::nextafterf;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1207:11: error: ‘::nextafterl’ has not been declared
   using ::nextafterl;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1209:11: error: ‘::nexttoward’ has not been declared
   using ::nexttoward;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1210:11: error: ‘::nexttowardf’ has not been declared
   using ::nexttowardf;
           ^~~~~~~~~~~
/usr/include/c++/6/cmath:1211:11: error: ‘::nexttowardl’ has not been declared
   using ::nexttowardl;
           ^~~~~~~~~~~
/usr/include/c++/6/cmath:1213:11: error: ‘::remainder’ has not been declared
   using ::remainder;
           ^~~~~~~~~
/usr/include/c++/6/cmath:1214:11: error: ‘::remainderf’ has not been declared
   using ::remainderf;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1215:11: error: ‘::remainderl’ has not been declared
   using ::remainderl;
           ^~~~~~~~~~
/usr/include/c++/6/cmath:1217:11: error: ‘::remquo’ has not been declared
   using ::remquo;
           ^~~~~~
/usr/include/c++/6/cmath:1218:11: error: ‘::remquof’ has not been declared
   using ::remquof;
           ^~~~~~~
/usr/include/c++/6/cmath:1219:11: error: ‘::remquol’ has not been declared
   using ::remquol;
           ^~~~~~~
/usr/include/c++/6/cmath:1221:11: error: ‘::rint’ has not been declared
   using ::rint;
           ^~~~
/usr/include/c++/6/cmath:1222:11: error: ‘::rintf’ has not been declared
   using ::rintf;
           ^~~~~
/usr/include/c++/6/cmath:1223:11: error: ‘::rintl’ has not been declared
   using ::rintl;
           ^~~~~
/usr/include/c++/6/cmath:1225:11: error: ‘::round’ has not been declared
   using ::round;
           ^~~~~
/usr/include/c++/6/cmath:1226:11: error: ‘::roundf’ has not been declared
   using ::roundf;
           ^~~~~~
/usr/include/c++/6/cmath:1227:11: error: ‘::roundl’ has not been declared
   using ::roundl;
           ^~~~~~
/usr/include/c++/6/cmath:1229:11: error: ‘::scalbln’ has not been declared
   using ::scalbln;
           ^~~~~~~
/usr/include/c++/6/cmath:1230:11: error: ‘::scalblnf’ has not been declared
   using ::scalblnf;
           ^~~~~~~~
/usr/include/c++/6/cmath:1231:11: error: ‘::scalblnl’ has not been declared
   using ::scalblnl;
           ^~~~~~~~
/usr/include/c++/6/cmath:1233:11: error: ‘::scalbn’ has not been declared
   using ::scalbn;
           ^~~~~~
/usr/include/c++/6/cmath:1234:11: error: ‘::scalbnf’ has not been declared
   using ::scalbnf;
           ^~~~~~~
/usr/include/c++/6/cmath:1235:11: error: ‘::scalbnl’ has not been declared
   using ::scalbnl;
           ^~~~~~~
/usr/include/c++/6/cmath:1237:11: error: ‘::tgamma’ has not been declared
   using ::tgamma;
           ^~~~~~
/usr/include/c++/6/cmath:1238:11: error: ‘::tgammaf’ has not been declared
   using ::tgammaf;
           ^~~~~~~
/usr/include/c++/6/cmath:1239:11: error: ‘::tgammal’ has not been declared
   using ::tgammal;
           ^~~~~~~
/usr/include/c++/6/cmath:1241:11: error: ‘::trunc’ has not been declared
   using ::trunc;
           ^~~~~
/usr/include/c++/6/cmath:1242:11: error: ‘::truncf’ has not been declared
   using ::truncf;
           ^~~~~~
/usr/include/c++/6/cmath:1243:11: error: ‘::truncl’ has not been declared
   using ::truncl;
           ^~~~~~
CMakeFiles/grizzly.dir/build.make:110: recipe for target 'CMakeFiles/grizzly.dir/Ooura/fftsg.cpp.o' failed
make[2]: *** [CMakeFiles/grizzly.dir/Ooura/fftsg.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/grizzly.dir/all' failed
make[1]: *** [CMakeFiles/grizzly.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DannyvanSwieten** [comment]
So the errors come from system headers...
It might have something to do with this manual's section on cmath.h:
https://gcc.gnu.org/gcc-6/porting_to.html
You can try reinstalling libstd++ and/or libstd++-dev
I won't be able to try and compile on linux untill after the weekend.

**Comment by ciskavriezenga** [comment]
reinstalling libstd++ -> errors 

Seems to be libstdc++6 is conflicting with 4.9



Prepared a new sd card with raspbian jessie image. 
Instead of installing gcc-6 the 'easy way': https://solarianprogrammer.com/2016/06/24/raspberry-pi-raspbian-install-gcc-compile-cpp-14-and-cpp-17-programs/
I used the more proper way: https://solarianprogrammer.com/2016/06/29/raspberry-pi-raspbian-compiling-gcc-6/

While trying to install cmake (necessary for bear-audio) similar errors rised, conflicts with libstd++6...

**Comment by ciskavriezenga** [comment]
@stijnfrishert 
You succeeded in installing bear-audio on pi. Did you encounter any issues? 
How did you install gcc-6?

**Comment by stijnfrishert** [comment]
Hi guys, just checking in. Inbetween moving houses, so can't really try stuff out, but I remember having this same issue with the first Raspbian image I made. The solution escapes me though :/

Just a list of thoughts:
 - Have you installed both gcc-6 and g++-6?
 - Are they both the default compilers?
 - Perhaps indeed you should install libstdc++-6 as well
 - I'd try compiling a simple main.c calling a `cos()` and see if that works. With and without c++14/17 flags

**Comment by ciskavriezenga** [comment]
@stijnfrishert did you use apt-get to install gcc-6 and g++-6? Does this mean you edited /etc/apt/sources.list and changed jessie to stretch? See - "The Easy Way" http://choccyhobnob.com/tutorials/gcc-6-on-raspberry-pi/

I did it "The Safe Way", did another reinstall, compiled GCC6 from scratch (this time I made an image after this, not want to do that again .. 14 hours of running make... ). 
I am now installing the dsperados libraries manually. Cmake works on all, so no issues like with 'the brew cmake'. But am now stuck with running make ('unit' went okay), /usr/binc++ is used instead of g++-6. So looking into configuring the compiler in cmake so make uses the correct one. 

Will be continued.. 
Compiler works by the way, tested it with a simple main.

**Comment by ciskavriezenga** [comment]
Manually install dsperados libraries
(brew gives a lot of issues)

First install gcc-6 compiler 
http://choccyhobnob.com/tutorials/gcc-6-on-raspberry-pi/ (not sure if “The Easy Way” wsi okay, “The Safe Way” is)



• install cmake
$ Sudo apt-get install cmake

For bear-audio the ALSA and SndFile libraries are necessary, install these:
$ Sudo apt-get install libasound2-dev
$ Sudo apt-get install libsndfile1-dev


• You first need to configure the compiler you want cmake to use. (also, be sure you added export PATH=/usr/local/gcc-6.2/bin:$PATH to ~/.profile & rebooted, or run $ PATH=/usr/local/gcc-6.2/bin:$PATH manually) run:
$ export CXX=gcc-6

• Create build directory, enter it, run cmake, etc., as explained on the dsperados libraries on github:
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install


Above works with all libraries, except for bear-audio and grizzly, still errors posted earlier

**Comment by ciskavriezenga** [comment]
I seem to have fixed it!! 

It turns out that Ooura/fftsg.cpp.o includes math.h inside a namespace. 
cmath first calls undef on acos & the others, then defines them inside std:: and later on calls ```using ::acosz```. It then can't find them. Could this be that instead of 'existing' in std:: they exist inside namespace dsp::std (Ooura/fftsg.cpp)? 

I moved the #include <math.h> to the top and then it works!

**Comment by DannyvanSwieten** [comment]
That's really stupid on our side *shame*.
Very awesome you've found it!
I'll commit a fix tonight.
